### ISSUE TITLE
Module not found: Error: Can't resolve 'preact-material-components/Toolbar/style.css'

### ISSUE THREAD

**Issue by JNaftali** [preactjs-templates/material#18]
After creating a project with `preact create material project-name`, running `npm run start` causes the above error. The problem comes from `components/header/index.js` on line 12, which tries to import  `'preact-material-components/Toolbar/style.css'` even though no such file exists in `node_modules`.

I assume this is an upstream error, but until it's addressed I'll probably just import the whole stylesheet at once instead of doing it per-component.

**Comment by prateekbh** [comment]
Oh yeah my bad, Toolbar is deprecated. Will update ASAP

**Comment by prateekbh** [comment]
fixed, can you re-create your project?

**Comment by JNaftali** [comment]
I'll give it a go - unless you hear otherwise assume it worked fine and thanks for your help!
